### PR TITLE
Check if Url exists before adding to cache

### PR DESCRIPTION
**Pull request by SteJW**
As suggested in the issue https://github.com/thoughtco/statamic-cache-tracker/issues/13, I added a check for the Url before adding it to cache.

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Thanks. I've refactored it a bit for performance, let me know how it works for you now.

**Comment by SteJW** [comment]
Perfect, thanks! I removed the now unused get method.

**Comment by ryanmitchell** [comment]
Thanks! Thats merged and released in 0.7.0

**Comment by SteJW** [comment]
Awesome! Thanks for your quick responses! Great addon you made here and I actually can't believe this isn't part of Statamic. Without it, caching is a real pain for content editors =)

**Pull request merged**
